### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by username-pass** [username-pass/bookmarklets#12]
Currently working on a new website.
Right now it is not public, but soon it will be open for Beta.

**Comment by pazza08223** [comment]
in the website can you do one of those things where you can just drag a link to the bookmark bar and get the bookmarklet. I have seen those and are cooler and more easy for my not so tech savy frends to get new bookmarklets.

**Comment by fowntain** [comment]
I can help, I have a lot of experience with frontend, check out my organization! https://github.com/Skoolgq

**Comment by username-pass** [comment]
How well do you know nodejs? This specific project requires nodejs and I cannot quite figure this out.

**Comment by username-pass** [comment]
That would help, but I also need to get the current URL of a site in nodeJS. What nodeJS experience do you have?
