### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ghost** [username-pass/bookmarklets#2]
the window pops up, but non of them work. or atleast i can find no defrence. i did better ctrl-f, saw no defrence to the find fuction. eny dependincy's or weard way to install?

**Comment by username-pass** [comment]
do not type in "better ctrl-f", type "22". If that does not work, then try things out on about:blank, some things (like zapper) are dysfunctional, and others, do not work on some sites.

**Comment by username-pass** [comment]
tell me if that works
