### ISSUE TITLE
youtube add skip dose not work

### ISSUE THREAD

**Issue by pazza08223** [username-pass/bookmarklets#22]
It dose not seam to work. I recomend removing it becsue resently google has ben trying to stop people from removing ads. (e.g. making manifest v3 required or braking brave ad blocker)

**Comment by username-pass** [comment]
I will look into it, my school has blocked bookmarklets, making it harder to test these things.

**Comment by pazza08223** [comment]
i code stuff at home. I am geting firefox installable on chromebook. also mega unbloker dose not work becuse it lodes a website with the words "unblock" or un, or block, of that sort, gogardean blockes that stuff.

**Comment by pazza08223** [comment]
oh, it is becuse it is a replit.

**Comment by username-pass** [comment]
Ad skip does work, I just tested it. You could pause the ad, then click it if it still does not work. It does not block ads, it skips them, so when an ad appears, you click the BML and then the ad skip. So it does not prevent ads.
