### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by Duggybud** [username-pass/bookmarklets#26]
how do i use the all bookmarklet one?

**Comment by username-pass** [comment]
that is the code for the bookmarklet, the real bookmarklet contains all bookmarklets in this repo

copy this code to a bookmark
```
javascript: fetch("https://raw.githubusercontent.com/username-pass/bookmarklets/main/all-depbookmarklets.js").then(function(response){response.text().then(function(text) {eval(text);});});
```

run it, and type the number of the bookmarklet you want. If you click away from the pop-up window or press escape, it will close itself.
